# Generated by Django 4.1.6 on 2023-02-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('reciver', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
