# Generated by Django 4.1.6 on 2023-02-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(max_length=20),
        ),
    ]
